---
# Source: apache/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: httpd-apache
  labels:
    app.kubernetes.io/name: apache
    helm.sh/chart: apache-8.11.1
    app.kubernetes.io/instance: httpd
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
  selector:
    app.kubernetes.io/name: apache
    app.kubernetes.io/instance: httpd
